# Generated by Django 6.0rc1 on 2026-01-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
