# Generated by Django 6.0rc1 on 2026-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email адрес*'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя*'),
        ),
    ]
