# Generated by Django 6.0rc1 on 2026-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0004_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='teacher_set_password',
            field=models.CharField(blank=True, help_text='Пароль, установленный учителем', max_length=128, null=True),
        ),
    ]
