# Generated by Django 6.0rc1 on 2026-01-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0005_studentapplication_teacher_set_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.SlugField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
