# Generated by Django 5.2.10 on 2026-02-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0009_webpushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.URLField(max_length=500),
        ),
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=300)),
                ('refresh_token', models.CharField(max_length=300)),
                ('token_expiry', models.DateTimeField()),
                ('calendar_id', models.CharField(default='primary', max_length=200)),
                ('user', models.OneToOneField(limit_choices_to={'usertype': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
