# Generated by Django 5.2.10 on 2026-02-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0010_alter_webpushsubscription_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
