# Generated by Django 5.2.10 on 2026-02-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0011_task_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendartoken',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
