# Generated by Django 5.2.10 on 2026-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0012_alter_googlecalendartoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendartoken',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='googlecalendartoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
