# Generated by Django 5.2.10 on 2026-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0013_alter_googlecalendartoken_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='calendar_event_id',
        ),
        migrations.AddField(
            model_name='task',
            name='student_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
