# Generated by Django 5.2.10 on 2026-02-10 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0014_remove_task_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendartoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
