# Generated by Django 5.2.10 on 2026-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0015_alter_googlecalendartoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
