# Generated by Django 5.2.10 on 2026-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0016_task_reminded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
